# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: LCC Digital Services
subtitle: Guides for our online services

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/lcc-guide'

# Author/Organization info to be displayed in the templates
author:
  name: Leicestershire County Council Digital Services Team
  url: http://www.leicestershire.gov.uk

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: http://leicestershire.gov.uk/sites/all/themes/lcc/img/logo.svg
logoalt: LCC logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Example Page
  url: example_page/
  internal: true
- text: DOCter Repo
  url: https://github.com/cfpb/DOCter
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Leics DST
  description: Jekyll template for docs
  url: https://github.com/leicsCC

# Style Variables
brand_color: "#5da631"
bg_color: "#21793b"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:

  # If defined and browserify and uglifyify are installed, the plugin will
  # generate a bundle to define the renderJekyllPagesApiSearchResults
  # function.
  browserify:
    source: js/my-search.js
    target: js/my-search-bundle.js
